apiVersion: v1
kind: Pod
metadata:
  labels:
    app: practicalmargulis-pod
  name: practicalmargulis-pod
spec:
  initContainers:
  - name: model-file
    image: quay.io/mmortari/ml-iris:v1-modelcar
    command: ['cp', "/models/model.joblib", "/shared/"]
    volumeMounts:
    - name: model-file
      mountPath: /shared
  containers:
  - command:
    - python
    - -m
    - sklearnserver
    - --model_dir
    - /models
    # env:
    # - name: TERM
    #   value: xterm
    image: docker.io/kserve/sklearnserver:latest
    name: practicalmargulis
    ports:
    - containerPort: 8080
      hostPort: 8080
    securityContext:
      runAsNonRoot: true
    # stdin: true
    # tty: true
    volumeMounts:
    - mountPath: /models
      name: model-file
  volumes:
  - name: model-file
    emptyDir: {}
