version: '3'
services:
  oml-integration-mlmd-server:
    image: gcr.io/tfx-oss-public/ml_metadata_store_server:1.14.0
    container_name: oml-integration-mlmd-server
    ports:
      - "9090:8080"
    environment:
      - METADATA_STORE_SERVER_CONFIG_FILE=/tmp/shared/conn_config.pb
    volumes:
      - ./mr-integration/config/ml-metadata:/tmp/shared
  oml-integration-model-registry:
    image: quay.io/opendatahub/model-registry:latest
    command: ["proxy", "--hostname", "0.0.0.0", "--mlmd-hostname", "oml-integration-mlmd-server", "--mlmd-port", "8080"]
    container_name: oml-integration-model-registry
    ports:
      - "8088:8080"
    depends_on:
      - oml-integration-mlmd-server
